// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Sidebar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<aside class=\"w-64 bg-gray-900 text-white h-screen flex flex-col\"><div class=\"p-4 border-b border-gray-800\"><h1 class=\"text-xl font-bold\">Labuh</h1></div><nav class=\"flex-1 p-4 space-y-2\"><a href=\"/dashboard\" class=\"block px-4 py-2 rounded\" :class=\"window.location.pathname === '/dashboard' ? 'bg-gray-800' : 'hover:bg-gray-800'\">Dashboard</a> <a href=\"/projects\" class=\"block px-4 py-2 rounded\" :class=\"window.location.pathname.startsWith('/projects') || window.location.pathname.startsWith('/templates') ? 'bg-gray-800' : 'hover:bg-gray-800'\">Projects</a> <a href=\"/templates\" class=\"block px-4 py-2 rounded\" :class=\"window.location.pathname === '/templates' ? 'bg-gray-800' : 'hover:bg-gray-800'\">Templates</a> <a href=\"#\" class=\"block px-4 py-2 rounded\" :class=\"window.location.pathname.startsWith('/applications') ? 'bg-gray-800' : 'hover:bg-gray-800'\">Applications</a> <a href=\"#\" class=\"block px-4 py-2 rounded\" :class=\"window.location.pathname.startsWith('/servers') ? 'bg-gray-800' : 'hover:bg-gray-800'\">Servers</a> <a href=\"/settings/api-keys\" class=\"block px-4 py-2 rounded\" :class=\"window.location.pathname.startsWith('/settings') ? 'bg-gray-800' : 'hover:bg-gray-800'\">Settings</a></nav><div class=\"p-4 border-t border-gray-800\"><form action=\"/auth/logout\" method=\"get\"><button type=\"submit\" class=\"w-full text-left px-4 py-2 rounded hover:bg-gray-800\">Logout</button></form></div></aside>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
