// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/akordium-id/get-labuh/internal/web/components"

func AppLayout(content templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Labuh</title><script src=\"https://cdn.tailwindcss.com\"></script><script src=\"https://unpkg.com/htmx.org@2.0.0\"></script><script defer src=\"https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js\"></script><script>\n\t\t\tdocument.addEventListener('htmx:configRequest', function(evt) {\n\t\t\t\tvar csrfToken = document.querySelector('meta[name=\"csrf-token\"]');\n\t\t\t\tif (csrfToken) {\n\t\t\t\t\tevt.detail.headers['X-CSRF-Token'] = csrfToken.getAttribute('content');\n\t\t\t\t} else {\n\t\t\t\t\tvar match = document.cookie.match(new RegExp('(^| )csrf_token=([^;]+)'));\n\t\t\t\t\tif (match) {\n\t\t\t\t\t\tevt.detail.headers['X-CSRF-Token'] = decodeURIComponent(match[2]);\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t});\n\t\t</script></head><body class=\"bg-gray-50\" x-data=\"{ sidebarOpen: false }\"><div class=\"flex h-screen\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Sidebar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"flex-1 flex flex-col min-w-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Topbar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div id=\"toast-container\" class=\"fixed top-4 right-4 z-50 hidden\"><div id=\"toast\" class=\"hidden bg-red-50 border border-red-200 text-red-800 px-4 py-3 rounded-md shadow-lg max-w-sm\"><p class=\"text-sm font-medium\" id=\"toast-message\">An error occurred</p></div></div><main id=\"main-content\" class=\"flex-1 overflow-auto p-6\" hx-on:htmx:error=\"handleHtmxError(event)\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</main></div></div><script>\n\t\t\tfunction handleHtmxError(event) {\n\t\t\t\tvar toast = document.getElementById('toast');\n\t\t\t\tvar toastMessage = document.getElementById('toast-message');\n\t\t\t\tvar toastContainer = document.getElementById('toast-container');\n\t\t\t\tif (toast && toastMessage && toastContainer) {\n\t\t\t\t\tvar status = event.detail.xhr ? event.detail.xhr.status : 0;\n\t\t\t\t\tvar message = 'Request failed with status ' + status;\n\t\t\t\t\tif (event.detail.xhr && event.detail.xhr.responseText) {\n\t\t\t\t\t\ttry {\n\t\t\t\t\t\t\tvar json = JSON.parse(event.detail.xhr.responseText);\n\t\t\t\t\t\t\tif (json.error) message = json.error;\n\t\t\t\t\t\t} catch(e) {}\n\t\t\t\t\t}\n\t\t\t\t\ttoastMessage.textContent = message;\n\t\t\t\t\ttoast.classList.remove('hidden');\n\t\t\t\t\ttoastContainer.classList.remove('hidden');\n\t\t\t\t\tsetTimeout(function() {\n\t\t\t\t\t\ttoast.classList.add('hidden');\n\t\t\t\t\t\ttoastContainer.classList.add('hidden');\n\t\t\t\t\t}, 5000);\n\t\t\t\t}\n\t\t\t}\n\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
